name: CI

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Execute Packer Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3

      - name: Prepare example vars
        run: cp ubuntu.pkrvars.hcl.example ubuntu.pkrvars.hcl

      - name: Run Validate
        run: make validate
